# Generated by Django 3.0.6 on 2020-06-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('DOB', models.DateTimeField()),
                ('speciality', models.CharField(max_length=100)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('facebook_link', models.CharField(blank=True, max_length=100)),
                ('instagram_link', models.CharField(blank=True, max_length=100)),
                ('linkedIn_link', models.CharField(blank=True, max_length=100)),
                ('twitter_link', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
