# Generated by Django 3.0.6 on 2020-06-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0003_auto_20200603_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chef',
            old_name='photo',
            new_name='photo_chef',
        ),
    ]
