# Generated by Django 3.0.6 on 2020-06-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20200607_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='month',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='year',
        ),
    ]
