# Generated by Django 3.0.6 on 2020-06-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='Photo/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='Tag',
            field=models.CharField(choices=[('starters', 'Starters'), ('salad', 'Salads'), ('Speciality', 'Speciality')], default=None, max_length=200),
        ),
    ]
