# Generated by Django 3.0.6 on 2020-06-03 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0004_auto_20200603_1356'),
        ('menu', '0002_auto_20200603_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='special',
            old_name='photo',
            new_name='photo_dish',
        ),
        migrations.AddField(
            model_name='special',
            name='chef',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='chefs.chef'),
            preserve_default=False,
        ),
    ]
