# Generated by Django 3.0.6 on 2020-06-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200603_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='Items',
            new_name='Ingredients',
        ),
    ]
