# Generated by Django 3.0.6 on 2020-06-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200603_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special',
            name='chef',
        ),
        migrations.AlterField(
            model_name='menu',
            name='Tag',
            field=models.CharField(choices=[('starters', 'Starters'), ('salads', 'Salads'), ('specialty', 'Specialty')], default=None, max_length=200),
        ),
    ]
